### ISSUE TITLE
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.

### ISSUE THREAD

**Issue by comradexy** [PRBonn/MaskPLS#6]
When running 'python3 scripts/train_model.py', there's an error below:

fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "scripts/train_model.py", line 84, in <module>
    main()
  File "/home/dxy/anaconda3/envs/maskpls/lib/python3.7/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/dxy/anaconda3/envs/maskpls/lib/python3.7/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/dxy/anaconda3/envs/maskpls/lib/python3.7/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dxy/anaconda3/envs/maskpls/lib/python3.7/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "scripts/train_model.py", line 32, in main
    subprocess.check_output(["git", "rev-parse", "--short", "HEAD"]).strip()
  File "/home/dxy/anaconda3/envs/maskpls/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/dxy/anaconda3/envs/maskpls/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'rev-parse', '--short', 'HEAD']' returned non-zero exit status 128.

**Comment by comradexy** [comment]
After commenting out or deleting the code on line 31 of **train_model.py**, it will run successfully.

For example:
\# cfg.git_commit_version = str(
\#     subprocess.check_output(["git", "rev-parse", "--short", "HEAD"]).strip()
\# )

**Comment by rmarcuzzi** [comment]
Hi! 
Thanks for pointing that out! I removed that line from the training script, I was using it to include the commit hash in the log.
